---
# Runs a basic staging playbook on new hosts prepared by provision_vms.yml

- name: Stage the new hosts
  hosts: deploy
  become: true
  roles:
  - role: stage_ubuntu
  - role: file_client
    