---
# tasks file for provisioning_ubuntu
# This play will be run as user smiledt
# This play adds the management user ansible
# It then adds the user to passwordless sudo (for now) to enable all other tasks to be done using ansible

- name: Add the management user {{ management_user }}
  user:
    name: "{{ management_user }}"
    password: "{{ management_pass }}"
    state: present
    update_password: always
  tags: [ 'configure' ]

- name: Ensure that the management user {{ management_user }} has sudo priveleges
  lineinfile: dest=/etc/sudoers.d/ansible create=yes state=present 
              line="{{ management_user }} ALL=(ALL) NOPASSWD:ALL"
  tags: [ 'configure' ]

- name: Set authorized SSH key for {{ management_user }}
  authorized_key: 
    user: ansible
    state: present 
    key: '{{ item }}'
  with_file:
    - files/{{ management_public_key }}

